### ISSUE TITLE
resolve before require

### ISSUE THREAD

**Issue by alandipert** [projectodd/shimdandy#1]
The [var method](https://github.com/projectodd/shimdandy/blob/394c804f12e320be86653f138d9c9e6d36a0d4e7/impl/src/main/java/org/projectodd/shimdandy/impl/ClojureRuntimeShimImpl.java#L36-50) requires the namespace no matter what.

This means that to `.invoke` a Var that doesn't live in a file, you need to mutate `#'clojure.core/*loaded-libs*` to trick Clojure into thinking it doesn't need to require again.  I suppose you could also spit the code into a file in the pod's classpath.

The question I want to ask is, would the world be a better place if `var` tried to resolve before requiring?

**Comment by tobias** [comment]
Fixed in 1.1.0.
