### ISSUE TITLE
Bindings destroyed

### ISSUE THREAD

**Issue by golanw** [projectodd/shimdandy#7]
We are using a Java application with clojure.
Clojure code can call java code and vice versa.
In a flow where Clojure -> Java -> Clojure
```
Main clojure code
  |
  (using clojure bindings here)
  |
  ----- Java function
             |
             |
             ------ Clojure function (using invoke)
                             |
                             |
             -----------------
             |
  ------------
  |
  |
 (binidings lost here after the clojure invocation)
  |
  |
```
The bindings are lost when finishing the invocation due to the dvals cleanup.

Is there a way to fix it or workaround it?

**Comment by tobias** [comment]
This is happening because the outer `RT.class` is visible to shimdandy, so you don't have classloader isolation, so aren't getting any benefit from shimdandy. In order for it to work, Clojure classes can't be visible via the classloader tree above the class that is using shimdandy (see https://github.com/projectodd/shimdandy#usage). Basically, Clojure can't be the entry point to your application - it has to be Java (or you have to do some nasty classloader hacks). 

I'm happy to chat about what you are trying to accomplish with shimdandy and see if we can figure out a way to do it.

**Comment by golanw** [comment]
Thanks for trying to help out here :)

So we had a pure Java application at first, but then we migrated to clojure.
After some time, unfortunately there's still a lot of Java code.
So you are correct - the entry point in this case is clojure - it's a httpkit clojure server.
Inside the call stack there's a Java function which uses the invoke.

I'm not sure how to solve this, since the setup of this project is quite complicated - we are starting as a Java application, there's one infrasrtructure clojure jar in the classpath and additionally we load all the other clojure namespaces at runtime. At some point we initialize the aforementioned httpkit clojure server.

I saw you added this "dvals cleanup" to prevent a memory leak.
I thought about maybe wrapping your code so I could keep the current dvals before the invoke, and setting it back after invoke completes.

What do you think?

**Comment by tobias** [comment]
At this point, you don't gain any benefit from using shimdandy, so I would recommend just dropping it entirely (if possible), and using [`clojure.java.api.Clojure`](https://www.clojure.org/reference/java_interop#_calling_clojure_from_java) instead.

If shimdandy is too interwoven into your app to remove now, you could extend `ClojureRuntimeShimImpl`, [override `preInvoke` and `postInvoke`](https://github.com/projectodd/shimdandy/blob/master/impl/src/main/java/org/projectodd/shimdandy/impl/ClojureRuntimeShimImpl.java#L32) to leave `dvals` alone, then use that, though you would have to also write your own version of [`ClojureRuntimeShim.newRuntime`](https://github.com/projectodd/shimdandy/blob/master/api/src/main/java/org/projectodd/shimdandy/ClojureRuntimeShim.java#L14) to load your Impl class.

**Comment by golanw** [comment]
Thank you @tobias 
Closing this issue - this scenario is simply not supported, and it's also mentioned in the usage instructions (https://github.com/projectodd/shimdandy#usage)
